'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class buy

    '''<summary>
    '''ddbook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddbook As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lsbook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbook As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbquan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbquan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lquan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lquan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbpm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbpm As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''tbnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lnm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbpno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lpno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lpno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lemail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbadd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ladd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ladd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbsi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbsi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnorder As Global.System.Web.UI.WebControls.Button
End Class
